### ISSUE TITLE
Create small UI framework for coalescing related preferences into a single page

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/gcloud-eclipse-tools#290]
As pointed out by @chanseokoh, we should have a way to [host conceptually-related preferences in a modular fashion](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/pull/255#issuecomment-228399095).

**Comment by chanseokoh** [comment]
Great! One thing to consider here is that the preference store I created in c.g.c.t.eclipse.preferences.Acviator is configuration-scoped (so that the setting is meant for a single Eclipse instance).

I'm not sure how this can be merged nicely with your instace-scope settings (which I believe is per workspace).

**Comment by briandealwis** [comment]
I'm thinking this just coalesces the UI into little fragments that behave like `PreferencePage`: `isValid()`, `performApply()`, `performCancel()`.  The actual preference storage is handled by the UI fragment.

**Comment by elharo** [comment]
Two options on the UI side:

1. A single preference "Google Cloud Tools"
2. A "Google Cloud Tools" category with subpages for Analytics, Cloud SDK, etc.

My gut is to go with the single preference page for now since we only have two actual preferences to set and then break it up later if we need to.

**Comment by rdayal** [comment]
+1, your suggestion make sense, Elliotte.

**Comment by briandealwis** [comment]
Work in progress in the https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/tree/prefareas branch.  Nearly finished — just want to put in some tests.
