### ISSUE TITLE
High DPI

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#356]
Test everything (icons especially) on a high DPI monitor and figure out what else we need to add. This may require eclipse neon. 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=421383

**Comment by briandealwis** [comment]
The icon looks small but it's functional.  I'm not sure why it's so small.

<img width="130" alt="login icon on hidpi win32" src="https://cloud.githubusercontent.com/assets/202851/17599784/b8d435e0-5fce-11e6-982a-839fef8746bf.PNG">

**Comment by briandealwis** [comment]
Turns out the [@2x icon that we provide](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/blob/39f2c0a94a01e6bd9f0314ecc55cc31ad04b5c25/plugins/com.google.cloud.tools.eclipse.appengine.login/icons/googleFavicon%402x.png) has a _lot_ of whitespace, so in fact it's as expected.

The [google.com favicon](https://www.google.ca/images/branding/product/ico/googleg_lodp.ico) has a much better 32x32 image.
