### ISSUE TITLE
Debug pane adds a new entry after each Dev Server run

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/gcloud-eclipse-tools#433]
When the user starts and restarts the App Engine Standard server, a new entry is added to the Debug pane. This doesn't happen with other local servers like Tomcat.

![debug_view](https://cloud.githubusercontent.com/assets/17732492/17067498/ef19893a-5019-11e6-8740-d802ca716a43.png)

@nbashirbello

**Comment by elharo** [comment]
My guess is that we're actually creating new servers. I.e. I don't think the problem is in the debug pane except insofar as it reflects the extra servers. Maybe something in the launch configuration?

**Comment by elharo** [comment]
OK, so that's not that's going on. If run the same server (not even debug it) repeatedly it does not appear more than once in the Servers view. However whenever I bring up the debug pane they're all there. 

I was careful to use an existing server and not define a new server when I ran it. 

I wonder if this might be expected behavior for the debug pane?

**Comment by briandealwis** [comment]
I think these correspond to the launch configurations for dev_appserver.py.  Our launch process then creates remote launch configurations that connect to the remote JVM. So our launch results in 2 slots in the _Debug_ pane, which seems odd in hindsight.  Perhaps these remote launches can be somehow placed under this top-level launch configuration.

**Comment by briandealwis** [comment]
The bug is that our Launch Configuration should be associating any launched processes with the provided _ILaunch_.  We're instead creating a new Remote Launch Configuration which is unassociated.
