### ISSUE TITLE
Sync workspace to disk after project creation from the tests

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#584]
This may be a cause of test flakiness

**Comment by briandealwis** [comment]
Our tests are failing on the assertion:
```
    protected IProject project;
[…]
    project = SwtBotAppEngineActions.createNativeWebAppProject(bot, projectName, location,
        packageName, projectId);
    assertTrue(project.exists());
```
`SwtBotAppEngineActions.createNativeWebAppProject()` creates and configures a New Project wizard, simulates a click on the _Finish_ button, and then waits for a window change — because the wizard is closed.

Our New Project wizards are using `WorkspaceModificationOperation`s to do their work (cf `CreateAppEngineStandardWtpProject`), which notes:

> The primary consequence of using this operation is that events which typically occur as a result of workspace changes (such as the firing of resource deltas, performance of auto builds, etc.) are generally deferred until the outermost operation has successfully completed.
> […]
> If a scheduling rule is provided, the operation will obtain that scheduling rule for the duration of its execute method. If no scheduling rule is provided, the operation will obtain a scheduling rule that locks the entire workspace for the duration of the operation.

We're not providing a scheduling rule, so our modifications are locking the workspace.

The `WorkspaceModificationOperation` is being performed by the `StandardProjectWizard#performFinish()` using its `getContainer().run(runnable)` operation.  That shows a progress bar within the wizard until the runnable completes.

So that `project.exists()` is false indicates one of a few things:

  1. The created project could have been deleted from disk.  This seems unlikely at this point in the test, since the project was being created.
  2. There's a race condition in the completion of the wizard and the update of the Eclipse workspace metadata with the created project. This would seem unlikely: the Eclipse Resources code has been around forever, and the workspace locking is key for how the different builders work.  It would imply that the workspace metadata may be inconsistent even after a workspace operation completes.
  3. The wizard is disappearing before the creation completes.  This seems unlikely, since the wizard should not be closed until the runnable completes.
  4. There may have been some other window change.  Hmm… I wonder if there's some shell change?

Regardless, I think a quick fix here is to use `SWTBot#waitUntil()` to wait until the project exists.
